name: release
inputs:
  release-note-name:
    type: string
    required: true
  tag:
    type: string
    required: true
  draft:
    type: boolean
    required: true
    default: true
outputs:
  release_name:
    description: "The new tag name"
    value: ${{ steps.release.outputs.release_name }}
runs:
  using: composite
  steps:
    - name: download-release-note
      uses: actions/download-artifact@v4
      with:
        name: ${{inputs.release-note-name}}
    - id: release
      shell: bash
      run: |
        noteFile="--generate-notes"
        draft=""
        # if a note file is generated, then create a release with the note
        if [ -f "CHANGELOG.md" ]; then
          noteFile="-F CHANGELOG.md"
        fi
        # if the tag is a draft release, then set the draft flag
        if ${{inputs.draft}}; then
          draft="--draft"
        fi
        today=$(date +"%Y-%m-%d")
        releaseName="$today-${{inputs.tag}}"
        gh release create ${{inputs.tag}} -t $releaseName $noteFile $draft
        echo "release_name=$releaseName" >> $GITHUB_OUTPUT
