name: release
inputs:
  tag:
    type: string
    required: true
  note:
    type: string
    required: false
  pre-release:
    type: boolean
    required: true
    default: true

runs:
  using: composite
  steps:
    - name: release
      shell: bash
      run: |
        preRelease=""
        noteStr="--generate-notes"
        # if the tag is a pre-release, then set the pre-release flag
        if ${{inputs.pre-release}}; then
        preRelease="-p"
        fi
        # if a note is provided, then create a release with the note
        if [ -n "$note" ]; then
        noteStr="-n $note"
        fi
        # create the release
        gh release create ${{inputs.tag}} $noteStr $preRelease
