name: release
inputs:
  tag:
    type: string
    required: true
  pre-release:
    type: boolean
    required: true
    default: true

runs:
  using: composite
  steps:
    - name: download-release-note
      uses: actions/download-artifact@v4
      with:
        name: ${{inputs.tag}}-release-note
    - name: check-file
      run: |
        ls -l
    - name: release
      shell: bash
      run: |
        preRelease=""
        # if the tag is a pre-release, then set the pre-release flag
        if ${{inputs.pre-release}}; then
        preRelease="-p"
        fi
        # create the release
        gh release create ${{inputs.tag}} -F ${{inputs.tag}}-release-note $preRelease
