name: release
inputs:
  tag:
    type: string
    required: true
  draft:
    type: boolean
    required: true
    default: true
runs:
  using: composite
  steps:
    - name: download-release-note
      uses: actions/download-artifact@v4
      with:
        name: ${{inputs.tag}}-release-note
    - name: release
      shell: bash
      run: |
        noteFile="--generate-notes"
        # if the tag is a draft release, then set the draft flag
        if ${{inputs.draft}}; then
          # if a note file is generated, then create a release with the note
          if [ -f "CHANGELOG.md" ]; then
          noteFile="-F CHANGELOG.md"
          fi
          # create the release
          gh release create ${{inputs.tag}} $noteFile --draft 
        else
          gh release create ${{inputs.tag}}
        fi
