name: find-latest-release
inputs:
  environment:
    type: string
    required: true
outputs:
  tag:
    description: "The latest release tag name"
    value: ${{ steps.find_latest.outputs.tag }}
runs:
  using: composite
  steps:
    - name: find-latest-release
      id: find_latest
      shell: bash
      run: |
        match_releases=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/justin8953/monorepo-commit-poc/releases --paginate --jq 'map(.tag_name | select(startswith("${{inputs.environment}}"))) | sort | reverse ')
        if [[ "$match_releases" = "null" ]]; then
          echo "No previous release found"
          echo "tag=" >> $GITHUB_OUTPUT
        else
          latest_tag=$(echo $match_releases | jq -r '.[0]')
          echo "Latest release is $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT
        fi
