name: release-note

runs:
  using: composite
  steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Create release note file
      shell: bash
      run: |
        prs=$(gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' \
        -X GET /repos/justin8953/monorepo-commit-poc/commits/${{github.ref}}/pulls --jq '.[].number')
        echo "## Release Note" > CHANGELOG.md
        for pr in $prs; do
          echo "PR: $pr"
          history=$(gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' \
            -X GET /repos/justin8953/monorepo-commit-poc/pulls/$pr/commits --jq '.[].commit | {message: .message, author: .author.name, date: .author.date, url: .url}')
          echo $history >> CHANGELOG.md
        done
        NOTE=$(cat CHANGELOG.md)
        echo ::set-output name=NOTE::$NOTE
