name: release-note

inputs:
  tag:
    description: "tag"
    required: true
  previous-tag:
    description: "previous tag"
runs:
  using: composite
  steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Create release note file
      shell: bash
      run: |
        pr=$(gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' \
        -X GET /repos/justin8953/monorepo-commit-poc/commits/${{inputs.tag}}/pulls --jq '.[].number')
        echo "PR: $pr"
        history=$(gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' \
          -X GET /repos/justin8953/monorepo-commit-poc/pulls/$pr/commits --jq 'map({message: .commit.message, author: .author.login, date: .commit.author.date, url: .commit.url})')
        echo $history >> CHANGELOG.json
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
    - name: generate release note
      shell: bash
      run: |
        yarn
        yarn run generate-changelog
    - name: get compare link
      shell: bash
      run: |
        if [ -z "${{inputs.previous-tag}}" ]; then
          echo "No previous tag"
          echo "This is new release. There is no full Changelog" >> CHANGELOG.md
        else
          compare=$(gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' \
            -X GET /repos/justin8953/monorepo-commit-poc/compare/${{inputs.previous-tag}}...${{inputs.tag}} --jq '.html_url')
          echo "Full Changelog:: $compare" >> CHANGELOG.md
        fi
    - name: upload release note
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.tag}}-release-note
        path: CHANGELOG.md
