name: release-note

inputs:
  tag:
    description: "tag"
    required: true
runs:
  using: composite
  steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Create release note file
      shell: bash
      run: |
        prs=$(gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' \
        -X GET /repos/justin8953/monorepo-commit-poc/commits/${{inputs.tag}}/pulls --jq '.[].number')
        pr=$(echo $prs | jq -r '.[0]')
        echo "PR: $pr"
        history=$(gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' \
          -X GET /repos/justin8953/monorepo-commit-poc/pulls/$pr/commits --jq 'map({message: .commit.message, author: .author.login, date: .commit.author.date, url: .commit.url})')
        echo $history >> CHANGELOG.json
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
    - name: generate release note
      shell: bash
      run: |
        yarn
        yarn run generate-changelog

    - name: upload release note
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.tag}}-release-note
        path: CHANGELOG.md
