name: delete-release
inputs:
  release_name:
    type: string
    required: true
runs:
  using: composite
  steps:
    - name: delete-release
      shell: bash
      run: |
        echo "Deleting release ${{ inputs.release_name }}"
        gh release delete ${{ inputs.release_name }} --yes
