name: tag
inputs:
  environment:
    type: string
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        ts=`date +%s%3N`
        TAG=${{ inputs.environment }}-$ts >> $GITHUB_OUTPUT
        echo create tag $TAG
        git tag $TAG
        git push origin --tags
