name: dto

on:
  push:
    paths:
      - "cores/dto/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          echo "Building..."
          echo "Build complete."
  pre-release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: tag
        id: git-tag
        shell: bash
        run: |
          ts=`date +%s%3N`
          TAG=staging-dto-$ts
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
          echo create tag $TAG
          git tag $TAG
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: generate-release-note
        uses: ./.github/workflows/common/release-note
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.git-tag.outputs.TAG }}
      - name: pre-release
        uses: ./.github/workflows/common/release
        with:
          pre-release: true
          tag: ${{ steps.git-tag.outputs.TAG }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: pre-release
    steps:
      - name: checkout
        uses: actions/checkout@v4
